package ai.dongsheng.model.entity;

import java.util.Date;

public class DevicePlaylist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.device_id
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.order_num
     *
     * @mbggenerated
     */
    private Long orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.album_id
     *
     * @mbggenerated
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.album_type
     *
     * @mbggenerated
     */
    private Byte albumType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.album_name
     *
     * @mbggenerated
     */
    private String albumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.res_id
     *
     * @mbggenerated
     */
    private Long resId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.res_type
     *
     * @mbggenerated
     */
    private Byte resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.res_name
     *
     * @mbggenerated
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.deleted
     *
     * @mbggenerated
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.sync_key
     *
     * @mbggenerated
     */
    private Long syncKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_playlist.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.id
     *
     * @return the value of device_playlist.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.id
     *
     * @param id the value for device_playlist.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.device_id
     *
     * @return the value of device_playlist.device_id
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.device_id
     *
     * @param deviceId the value for device_playlist.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.order_num
     *
     * @return the value of device_playlist.order_num
     *
     * @mbggenerated
     */
    public Long getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.order_num
     *
     * @param orderNum the value for device_playlist.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Long orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.album_id
     *
     * @return the value of device_playlist.album_id
     *
     * @mbggenerated
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.album_id
     *
     * @param albumId the value for device_playlist.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.category_id
     *
     * @return the value of device_playlist.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.category_id
     *
     * @param categoryId the value for device_playlist.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.album_type
     *
     * @return the value of device_playlist.album_type
     *
     * @mbggenerated
     */
    public Byte getAlbumType() {
        return albumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.album_type
     *
     * @param albumType the value for device_playlist.album_type
     *
     * @mbggenerated
     */
    public void setAlbumType(Byte albumType) {
        this.albumType = albumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.album_name
     *
     * @return the value of device_playlist.album_name
     *
     * @mbggenerated
     */
    public String getAlbumName() {
        return albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.album_name
     *
     * @param albumName the value for device_playlist.album_name
     *
     * @mbggenerated
     */
    public void setAlbumName(String albumName) {
        this.albumName = albumName == null ? null : albumName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.res_id
     *
     * @return the value of device_playlist.res_id
     *
     * @mbggenerated
     */
    public Long getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.res_id
     *
     * @param resId the value for device_playlist.res_id
     *
     * @mbggenerated
     */
    public void setResId(Long resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.res_type
     *
     * @return the value of device_playlist.res_type
     *
     * @mbggenerated
     */
    public Byte getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.res_type
     *
     * @param resType the value for device_playlist.res_type
     *
     * @mbggenerated
     */
    public void setResType(Byte resType) {
        this.resType = resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.res_name
     *
     * @return the value of device_playlist.res_name
     *
     * @mbggenerated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.res_name
     *
     * @param resName the value for device_playlist.res_name
     *
     * @mbggenerated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.deleted
     *
     * @return the value of device_playlist.deleted
     *
     * @mbggenerated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.deleted
     *
     * @param deleted the value for device_playlist.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.sync_key
     *
     * @return the value of device_playlist.sync_key
     *
     * @mbggenerated
     */
    public Long getSyncKey() {
        return syncKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.sync_key
     *
     * @param syncKey the value for device_playlist.sync_key
     *
     * @mbggenerated
     */
    public void setSyncKey(Long syncKey) {
        this.syncKey = syncKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.create_time
     *
     * @return the value of device_playlist.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.create_time
     *
     * @param createTime the value for device_playlist.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_playlist.update_time
     *
     * @return the value of device_playlist.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_playlist.update_time
     *
     * @param updateTime the value for device_playlist.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}